# Generated by Django 3.1.1 on 2020-10-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='reports_to',
        ),
    ]
