# Generated by Django 3.1.1 on 2020-10-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='reports_to',
            field=models.ManyToManyField(to='contributors.Contributor'),
        ),
    ]
