# Generated by Django 3.1.1 on 2020-10-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
