# Generated by Django 3.1.1 on 2021-12-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0004_auto_20211007_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='eligible_for_task_points',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='pay_per_day',
        ),
    ]
