# Generated by Django 3.1.1 on 2021-12-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0005_auto_20211207_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='visible',
        ),
    ]
