# Generated by Django 3.1.1 on 2020-10-09 19:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '0002_auto_20201008_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('pay_per_day', models.PositiveIntegerField()),
                ('eligible_for_task_points', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('categories', models.ManyToManyField(to='meta.Category')),
                ('responsibilities', models.ManyToManyField(to='meta.Responsibility')),
                ('skills', models.ManyToManyField(to='meta.Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
