# Generated by Django 3.1.1 on 2020-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('opening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='reports_to',
            field=models.ManyToManyField(to='team.Contributor'),
        ),
    ]
