# Generated by Django 3.1.3 on 2021-04-18 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0016_auto_20210413_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('github_url', models.URLField()),
                ('overview', models.TextField()),
                ('problem', models.TextField()),
                ('target_market', models.TextField()),
                ('benefits', models.TextField()),
                ('centered_around_tnb', models.CharField(max_length=250)),
                ('estimated_completion_date', models.DateTimeField()),
                ('project_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.projectmember')),
            ],
            options={
                'ordering': ('created_date', 'title'),
            },
        ),
    ]
