# Generated by Django 3.1.3 on 2021-04-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='project',
            name='centered_around_tnb',
            field=models.TextField(),
        ),
    ]
