# Generated by Django 3.1.1 on 2020-11-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201103_1944'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userearnings',
            name='unique_repository_time_period',
        ),
        migrations.AddConstraint(
            model_name='userearnings',
            constraint=models.UniqueConstraint(fields=('repository', 'time_period', 'user'), name='unique_repository_time_period_user'),
        ),
    ]
