# Generated by Django 3.1.1 on 2020-12-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
        ('users', '0005_auto_20201205_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userearnings',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_earnings', to='repositories.repository'),
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
