# Generated by Django 3.1.3 on 2021-04-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210309_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slack_username',
            new_name='discord_username',
        ),
    ]
