# Generated by Django 3.1.3 on 2022-01-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_app_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='page_hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
