# Generated by Django 3.1.1 on 2020-10-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_auto_20201010_2146'),
        ('contributors', '0001_initial'),
        ('tasks', '0002_auto_20201010_2146'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contributors',
            field=models.ManyToManyField(through='teams.TeamContributor', to='contributors.Contributor'),
        ),
        migrations.AlterField(
            model_name='teamcontributor',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributors.contributor'),
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
    ]
