# Generated by Django 3.1.1 on 2020-10-24 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_auto_20201024_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'default_related_name': 'team_members'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
