# Generated by Django 3.1.3 on 2020-12-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201024_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(default='OldJob', max_length=250),
            preserve_default=False,
        ),
    ]
