# Generated by Django 3.1.1 on 2020-12-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201024_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
