# Generated by Django 3.1.1 on 2020-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teammember_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='job_title',
            field=models.CharField(max_length=250),
        ),
    ]
