# Generated by Django 3.1.3 on 2020-12-22 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teammember_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('created_date', 'title')},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'default_related_name': 'team_members', 'ordering': ('created_date', 'job_title')},
        ),
    ]
