# Generated by Django 3.1.3 on 2021-02-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20201222_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
