# Generated by Django 3.1.6 on 2021-02-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_slackchannel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slackchannel',
            options={'default_related_name': 'slack_channels', 'ordering': ('created_date', 'name')},
        ),
        migrations.AlterField(
            model_name='slackchannel',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_channels', to='teams.team'),
        ),
    ]
