# Generated by Django 3.1.6 on 2021-03-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20210310_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.team')),
                ('responsibilities', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('teams.team',),
        ),
    ]
