# Generated by Django 3.1.6 on 2021-03-12 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_projectteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('teammember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.teammember')),
            ],
            options={
                'abstract': False,
            },
            bases=('teams.teammember',),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='pay_per_day',
        ),
        migrations.CreateModel(
            name='CoreMember',
            fields=[
                ('teammember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.teammember')),
                ('pay_per_day', models.PositiveIntegerField(default=2800)),
            ],
            options={
                'abstract': False,
            },
            bases=('teams.teammember',),
        ),
    ]
