# Generated by Django 3.1.6 on 2021-03-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_projectteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('teammember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='project_members', serialize=False, to='teams.teammember')),
                ('project_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='teams.projectteam')),
            ],
            options={
                'default_related_name': 'project_members',
            },
            bases=('teams.teammember',),
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='pay_per_day',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='teams.team'),
        ),
        migrations.CreateModel(
            name='CoreMember',
            fields=[
                ('teammember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_members', serialize=False, to='teams.teammember')),
                ('pay_per_day', models.PositiveIntegerField(default=2800)),
                ('core_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_members', to='teams.coreteam')),
            ],
            options={
                'default_related_name': 'core_members',
            },
            bases=('teams.teammember',),
        ),
        migrations.DeleteModel(
            name='SlackChannel',
        ),
    ]
