# Generated by Django 3.1.6 on 2021-04-12 19:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20210324_0602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='slack',
            new_name='discord',
        ),
        migrations.AddField(
            model_name='coreteam',
            name='responsibility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
