# Generated by Django 3.1.6 on 2021-04-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20210412_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreteam',
            name='responsibilities',
        ),
    ]
