# Generated by Django 3.1.6 on 2021-04-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_remove_coreteam_responsibilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreteam',
            old_name='responsibility',
            new_name='responsibilities',
        ),
    ]
