# Generated by Django 3.1.3 on 2020-12-26 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
    ]
