# Generated by Django 3.1.3 on 2021-02-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210212_1011'),
        ('repositories', '0002_auto_20201226_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
