# Generated by Django 3.1.6 on 2021-07-20 11:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'analytics',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('value', models.PositiveIntegerField()),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.analytics')),
            ],
            options={
                'verbose_name': 'analytics_data',
                'verbose_name_plural': 'analytics data',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCategory',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('analytics', models.ManyToManyField(blank=True, to='analytics.Analytics')),
            ],
            options={
                'verbose_name': 'analytics_category',
                'verbose_name_plural': 'analytics categories',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='analytics',
            name='data',
            field=models.ManyToManyField(blank=True, related_name='analytics_data', to='analytics.AnalyticsData'),
        ),
    ]
