# Generated by Django 3.1.6 on 2021-06-06 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projects_approved', models.PositiveIntegerField()),
                ('projects_completed', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'community',
                'ordering': ('week_ending',),
            },
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_coins_distributed', models.PositiveIntegerField()),
                ('total_coins_distributed_to_core_team', models.PositiveIntegerField()),
                ('total_coins_distributed_to_faucet', models.PositiveIntegerField()),
                ('total_coins_distributed_to_projects', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'economy',
                'ordering': ('week_ending',),
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_nodes', models.PositiveIntegerField()),
                ('total_transactions', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'network',
                'ordering': ('week_ending',),
            },
        ),
    ]
