# Generated by Django 3.1.6 on 2021-06-07 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actions_on_page', models.PositiveIntegerField()),
                ('page_views', models.PositiveIntegerField()),
                ('page_likes', models.PositiveIntegerField()),
                ('post_reach', models.PositiveIntegerField()),
                ('story_reach', models.PositiveIntegerField()),
                ('recommendations', models.PositiveIntegerField()),
                ('post_engagement', models.PositiveIntegerField()),
                ('responsiveness', models.PositiveIntegerField()),
                ('videos', models.PositiveIntegerField()),
                ('followers', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'facebook',
                'ordering': ('week_ending',),
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_reached', models.PositiveIntegerField()),
                ('impressions', models.PositiveIntegerField()),
                ('profile_visits', models.PositiveIntegerField()),
                ('website_taps', models.PositiveIntegerField()),
                ('content_interactions', models.PositiveIntegerField()),
                ('followers', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'instagram',
                'ordering': ('week_ending',),
            },
        ),
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('views', models.PositiveIntegerField()),
                ('unique_visitors', models.PositiveIntegerField()),
                ('custom_button_clicks', models.PositiveIntegerField()),
                ('reactions', models.PositiveIntegerField()),
                ('comments', models.PositiveIntegerField()),
                ('shares', models.PositiveIntegerField()),
                ('page_follow', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'linkedin',
                'ordering': ('week_ending',),
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tweets', models.PositiveIntegerField()),
                ('profile_visits', models.PositiveIntegerField()),
                ('total_followers', models.PositiveIntegerField()),
                ('new_followers', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'twitter',
                'ordering': ('week_ending',),
            },
        ),
    ]
