# Generated by Django 3.1.6 on 2021-06-07 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_facebook_instagram_linkedin_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSocial',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discord_members', models.PositiveIntegerField()),
                ('reddit_subscribers', models.PositiveIntegerField()),
                ('youtube_subscribers', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'ordering': ('week_ending',),
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('users', models.PositiveIntegerField()),
                ('sessions', models.PositiveIntegerField()),
                ('bounce_rate', models.FloatField()),
                ('session_duration', models.PositiveIntegerField()),
                ('week_ending', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'website',
                'ordering': ('week_ending',),
            },
        ),
    ]
