# Generated by Django 3.1.1 on 2020-10-11 22:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=250)),
                ('github_username', models.CharField(blank=True, max_length=250)),
                ('profile_image', models.FileField(blank=True, upload_to='')),
                ('slack_username', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
