# Generated by Django 3.1.1 on 2020-10-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_contributor_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
