# Generated by Django 3.1.1 on 2021-02-09 19:53

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('playlist_id', models.CharField(max_length=11)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=250)),
                ('thumbnail', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('playlist_type', models.CharField(default='youtube', editable=False, max_length=15)),
            ],
            options={
                'ordering': ('published_at',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.CharField(max_length=15)),
                ('duration', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=250)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=500)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, size=None)),
                ('thumbnail', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('video_type', models.CharField(default='youtube', editable=False, max_length=15)),
            ],
            options={
                'ordering': ('published_at',),
            },
        ),
    ]
