# Generated by Django 3.1.1 on 2021-02-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_type',
            field=models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'vimeo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'vimeo')], max_length=15),
        ),
    ]
