# Generated by Django 3.1.1 on 2021-02-10 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(editable=False, max_length=11),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250, null=True), blank=True, default=list, size=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(editable=False, max_length=11),
        ),
    ]
