# Generated by Django 3.1.1 on 2021-02-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210211_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'default_related_name': 'videos', 'ordering': ('published_at',)},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='items',
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.playlist'),
        ),
    ]
