# Generated by Django 3.1.6 on 2021-03-27 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210324_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('created_date',),
            },
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='playlist',
            name='categories',
            field=models.ManyToManyField(to='videos.Category'),
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='videos', to='videos.Category'),
        ),
    ]
