# Generated by Django 3.1.6 on 2021-03-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20210327_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created_date',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
