# Generated by Django 3.1.1 on 2021-10-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210513_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
